quarkus.http.port=4008
quarkus.http.host=0.0.0.0
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
quarkus.http.cors.headers=/.*/
# Storage backend: "local" or "s3"
media.storage.type=s3

# Local storage paths (used when media.storage.type=local)
media.path=/tmp/media-it
media.secured.path=/tmp/secured-media-it

# S3 / MinIO config (used when media.storage.type=s3)
# Switch media.storage.type=s3 and fill in real credentials to test against MinIO
media.s3.bucket=media-it

quarkus.s3.endpoint-override=http://172.27.76.227:9000
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=8t9HBTEgwiwUXCRszPEF
quarkus.s3.aws.credentials.static-provider.secret-access-key=dOB2iCLbuerbUpyWP29YJXCUVVv4rf6Jfrw7PFrr
quarkus.s3.devservices.enabled=false