package io.yanmastra.quarkus.rediscache;

import io.quarkus.runtime.annotations.ConfigPhase;
import io.quarkus.runtime.annotations.ConfigRoot;
import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithDefault;
import io.smallrye.config.WithName;

/**
 * The connection itself is configured with the standard Quarkus Redis client properties
 * ({@code quarkus.redis.hosts}, {@code quarkus.redis.password}, ...).
 */
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
@ConfigMapping(prefix = "cache.redis")
public interface RedisCacheConfig {

    /**
     * Store the key/value cache in Redis. When {@code false} the cache stays in local files, and any data that is
     * still in Redis is moved back into local files at start-up. To finish moving back, run once with
     * {@code false} and then remove the extension.
     */
    @WithDefault("true")
    boolean enabled();

    /**
     * Prefix of every Redis key written by this extension. Each cache is one Redis hash named
     * {@code <prefix>:<cacheName>}; {@code <prefix>:meta:*} is reserved for the encryption key and locks.
     */
    @WithName("key-prefix")
    @WithDefault("kvcache")
    String keyPrefix();

    /**
     * Encrypt values with AES-GCM before they are written to Redis. The key is generated by the first instance and
     * kept in Redis, so all instances share it. Keep this setting the same across all instances and restarts.
     */
    @WithDefault("true")
    boolean encrypt();
}
