quarkus.http.port=4099
quarkus.devservices.enabled=false
quarkus.log.category."io.yanmastra".level=DEBUG

# Error mail notification config
error-mail-notification.enabled=true
error-mail-notification.recipients=test-admin@example.com,test-ops@example.com
error-mail-notification.from=noreply@test.com
error-mail-notification.subject-prefix=[TEST ERROR]
error-mail-notification.app-name=integration-test-app
error-mail-notification.cooldown-seconds=5

# Quarkus mailer mock is enabled by default in test/dev mode
